version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/var/www
    networks:
      - app-network

  nginx:
    image: nginx:1.23-alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge